### ISSUE TITLE
[PE-D][Tester E] editprofile, viewprofile's expected output does not include BMI in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#173] opened 2023-11-03 16:23 UTC
No details provided by bug reporter.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: nihalzp/ped#5

**Comment by ICubE-** [comment] 2023-11-04 10:53
Duplicate of #166 and #169

**Closed by ICubE-** 2023-11-04 10:53 UTC
