### ISSUE TITLE
[PE-D][Tester B] storage error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#210] opened 2023-11-03 16:56 UTC
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/TriciaBK/ped/main/files/923a705c-ded6-4927-9f2d-1636df2fd1f9.png)

String stating Problem loading content after reopening the jar file occasionally - regardless of whether 'save' called after edits before exiting in the previous run.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: TriciaBK/ped#13

**Comment by ICubE-** [comment] 2023-11-06 14:55
Duplicate of #168

**Closed by ICubE-** 2023-11-06 14:55 UTC
