### ISSUE TITLE
[PE-D][Tester A] Unclear instructions for starting application

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-4/tp#176] opened 2023-11-03 16:24 UTC
Perhaps in the UG or in the greeting message when the application is first launched there should be an instruction to tell the user to enter their BMI first

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: DextheChik3n/ped#3

**Comment by ICubE-** [comment] 2023-11-04 10:50
Duplicate of #162

**Closed by ICubE-** 2023-11-04 10:50 UTC
