### ISSUE TITLE
[PE-D][Tester D] unknown syntax from the start

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-W12-4/tp#163] opened 2023-11-03 16:21 UTC
Upon running the program, it tells me to input my height, weight and calorie limit. However, it does not say in what syntax to do so. I have to fail once before I am able to get the syntax

![image.png](https://raw.githubusercontent.com/bnjm2000/ped/main/files/acad82db-9c95-4569-899d-6aadd5a89364.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bnjm2000/ped#1

**Comment by ICubE-** [comment] 2023-11-04 10:46
Duplicate of #162

**Closed by ICubE-** 2023-11-04 10:46 UTC
