### ISSUE TITLE
[PE-D][Tester A] addworkout command in UG not consistent with example usage 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#201] opened 2023-11-03 16:32 UTC
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/DextheChik3n/ped/main/files/5d8c583f-49fb-4543-adae-66c46b9786ec.png)

Perhaps you should update the command format to include the date argument

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: DextheChik3n/ped#7

**Comment by ICubE-** [comment] 2023-11-04 11:04
Duplicate of #174

**Closed by ICubE-** 2023-11-04 11:04 UTC
