### ISSUE TITLE
[PE-D][Tester E] UG does not cover opening query about health data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-W12-4/tp#164] opened 2023-11-03 16:21 UTC
UG does not mention that once opened, the app will ask for user height, weight and calorie limit.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: nihalzp/ped#2

**Comment by ICubE-** [comment] 2023-11-04 10:42
Duplicate of #161

**Closed by ICubE-** 2023-11-04 10:42 UTC

**Comment by ICubE-** [comment] 2023-11-04 10:45
Duplicate of #162
